EJERCICIO 1

In [1]:
a = "Hello, World!"
print(a.upper()) #Colocar mayusculas los valores

HELLO, WORLD!


EJERCICIO 2

In [2]:
a = "Hello, World!"
print(a.lower())

hello, world!


EJERCICIO 3

In [3]:
a = " Hello, World! "
print(a.strip()) # returns "Hello, World!"

Hello, World!


EJERCICIO 4

In [4]:
a = "Hello, World!"
print(a.replace("H", "J"))##REEPLAZAR H POR LA J

Jello, World!


EJERCICIO 5

In [10]:
a = "Hello,World!"
print(a.split(",")) # returns ['Hello', ' World!']

['Hello', 'World!']


capitalize()     => Convierte el primer carácter en mayúscula
casefold()        => Convierte la cadena en minúsculas
center()          => Devuelve una cadena centrada
count()           => Devuelve el número de veces que ocurre un valor especificado en una cadena
encode()          => Devuelve una versión codificada de la cadena
endswith()        => Devuelve True si la cadena termina con el valor especificado
expandtabs()      => Establece el tamaño de la tabulación de la cadena
find()            => Busca el valor especificado en una cadena y devuelve la posición donde se encontró
format()          => Formatea valores especificados en una cadena
format_map()      => Formatea valores especificados en una cadena
index()           => Busca el valor especificado en una cadena y devuelve la posición donde se encontró
isalnum()         => Devuelve True si todos los caracteres de la cadena son alfanuméricos
isalpha()         => Devuelve True si todos los caracteres de la cadena están en el alfabeto
isascii()         => Devuelve True si todos los caracteres de la cadena son caracteres ASCII
isdecimal()       => Devuelve True si todos los caracteres de la cadena son decimales
isdigit()         => Devuelve True si todos los caracteres de la cadena son dígitos
isidentifier()    => Devuelve True si la cadena es un identificador
islower()         => Devuelve True si todos los caracteres de la cadena están en minúsculas
isnumeric()       => Devuelve True si todos los caracteres de la cadena son numéricos
isprintable()     => Devuelve True si todos los caracteres de la cadena son imprimibles
isspace()         => Devuelve True si todos los caracteres de la cadena son espacios en blanco
istitle()         => Devuelve True si la cadena sigue las reglas de un título
isupper()         => Devuelve True si todos los caracteres de la cadena están en mayúsculas
join()            => Convierte los elementos de un iterable en una cadena
ljust()           => Devuelve una versión justificada a la izquierda de la cadena
lower()           => Convierte una cadena en minúsculas
lstrip()          => Devuelve una versión recortada a la izquierda de la cadena
maketrans()       => Devuelve una tabla de traducción para ser utilizada en traducciones
partition()       => Devuelve una tupla donde la cadena está dividida en tres partes
replace()         => Devuelve una cadena donde un valor especificado es reemplazado por otro valor especificado
rfind()           => Busca el valor especificado en una cadena y devuelve la última posición donde se encontró
rindex()          => Busca el valor especificado en una cadena y devuelve la última posición donde se encontró
rjust()           => Devuelve una versión justificada a la derecha de la cadena
rpartition()      => Devuelve una tupla donde la cadena está dividida en tres partes
rsplit()          => Divide la cadena en el separador especificado y devuelve una lista
rstrip()          => Devuelve una versión recortada a la derecha de la cadena
split()           => Divide la cadena en el separador especificado y devuelve una lista
splitlines()      => Divide la cadena en saltos de línea y devuelve una lista
startswith()      => Devuelve True si la cadena comienza con el valor especificado
strip()           => Devuelve una versión recortada de la cadena
swapcase()        => Intercambia mayúsculas por minúsculas y viceversa
title()           => Convierte el primer carácter de cada palabra en mayúscula
translate()       => Devuelve una cadena traducida
upper()           => Convierte una cadena en mayúsculas
zfill()           => Rellena la cadena con un número especificado de valores 0 al principio

EJERCICIO 6

In [11]:
age = 36
txt = "My name is John, and I am {}"
print(txt.format(age))

My name is John, and I am 36


EJERCICIO 7

In [13]:
quantity = 3
itemno = 567
price = 49.95
myorder = "I want to pay {0} dollars for {0} pieces of item {1}."
print(myorder.format(quantity, itemno, price))

I want to pay 3 dollars for 3 pieces of item 567.


Código     Resultado
\'         Comilla simple
\\         Barra invertida
\n         Nueva línea
\r         Retorno de carro
\t         Tabulación
\b         Retroceso
\f         Avance de página
\ooo       Valor octal
\xhh       Valor hexadecimal


In [1]:
thislist = ["apple", "banana", "cherry"]
thislist.append("orange")
print(thislist)

['apple', 'banana', 'cherry', 'orange']


In [6]:
list=["casa","madre","perros"]
list.insert(1,"ladrar")
print(list)

['casa', 'ladrar', 'madre', 'perros']


EJERCICIO 8

In [7]:
thislist = ["apple", "banana", "cherry"]
tropical = ["mango", "pineapple", "papaya"]

thislist.extend(tropical)

print(thislist)


['apple', 'banana', 'cherry', 'mango', 'pineapple', 'papaya']


EJERCICIO 8

In [10]:
thislist = ["apple", "banana", "cherry"]
thistuple = ("kiwi", "orange")
thislist.extend(thistuple)
print(thislist)

['apple', 'banana', 'cherry', 'kiwi', 'orange']


EJERCICIO 9

In [11]:
thislist = ["apple", "banana", "cherry"]
thislist.remove("banana")
print(thislist)

['apple', 'cherry']


EJERCICIO 10

In [12]:
thislist = ["apple", "banana", "cherry"]
thislist.pop(1)
print(thislist)

['apple', 'cherry']


EJERCICIO 11

In [13]:
thislist = ["apple", "banana", "cherry"]
del thislist[0]
print(thislist)

['banana', 'cherry']


EJERCICIO 12

In [14]:
thislist = ["apple", "banana", "cherry"]
thislist.clear()
print(thislist)

[]


EJERCICO 13

In [15]:
thislist = ["apple", "banana", "cherry"]
for x in thislist:
  print(x)

apple
banana
cherry


EJERCICO 14

In [16]:
thislist = ["apple", "banana", "cherry"]
for i in range(len(thislist)):
  print(thislist[i])

apple
banana
cherry


EJERCICIO 15

In [17]:
thislist = ["apple", "banana", "cherry"]
i = 0
while i < len(thislist):
  print(thislist[i])
  i = i + 1

apple
banana
cherry


EJERCICIO 16

In [18]:
thislist = ["apple", "banana", "cherry"]
[print(x) for x in thislist]

apple
banana
cherry


[None, None, None]

EJERCICIO 17

In [19]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist = []

for x in fruits:
  if "a" in x:
    newlist.append(x)

print(newlist)

['apple', 'banana', 'mango']


EJERCICIO 18

In [21]:
newlist = [x for x in range(10) if x < 5]
print(newlist)

[0, 1, 2, 3, 4]


EJERCICIO 19

In [22]:
thislist = ["orange", "mango", "kiwi", "pineapple", "banana"]
thislist.sort()
print(thislist)

['banana', 'kiwi', 'mango', 'orange', 'pineapple']


EJERCICIO 20

In [23]:
thislist = ["orange", "mango", "kiwi", "pineapple", "banana"]
thislist.sort(reverse = True)
print(thislist)

['pineapple', 'orange', 'mango', 'kiwi', 'banana']


EJERCICIO 21

In [24]:
def myfunc(n):
  return abs(n - 50)

thislist = [100, 50, 65, 82, 23]
thislist.sort(key = myfunc)
print(thislist)

[50, 65, 23, 82, 100]


EJERCICIO 21

In [25]:
thislist = ["banana", "Orange", "Kiwi", "cherry"]
thislist.sort(key = str.lower)
print(thislist)

['banana', 'cherry', 'Kiwi', 'Orange']


EJERCICIO 22

In [26]:
thislist = ["apple", "banana", "cherry"]
mylist = thislist.copy()
print(mylist)

['apple', 'banana', 'cherry']


EJERCICIO 23

In [29]:
thislist = ["apple", "banana", "cherry"]
mylist = thislist[:]
print(mylist)

['apple', 'banana', 'cherry']


EJERCICIO 24

In [32]:
list1 = ["a", "b" , "c"]
list2 = [1, 2, 3]

for x in list2:
  list1.append(x)

print(list1)

['a', 'b', 'c', 1, 2, 3]


EJERCICIO 25

In [31]:
list1=[1,2,3]
list2=[2,4,5]

list3=list1+list2
print(list3)

[1, 2, 3, 2, 4, 5]


EJERCICIO 26

In [33]:
list1 = ["a", "b" , "c"]
list2 = [1, 2, 3]

list1.extend(list2)
print(list1)

['a', 'b', 'c', 1, 2, 3]


append(): Agrega un elemento al final de la lista.
clear(): Elimina todos los elementos de la lista.
copy(): Devuelve una copia de la lista.
count(): Devuelve el número de elementos con el valor especificado.
extend(): Agrega los elementos de una lista (o cualquier iterable) al final de la lista actual.
index(): Devuelve el índice del primer elemento con el valor especificado.
insert(): Agrega un elemento en la posición especificada.
pop(): Elimina el elemento en la posición especificada.
remove(): Elimina el elemento con el valor especificado.
reverse(): Invierte el orden de la lista.
sort(): Ordena la lista.

EJERCICIO 27

In [35]:
fruits = ["apple", "banana", "cherry"]
print(len(fruits))

3


EJERCICIO 28

In [1]:
x = ("apple", "banana", "cherry")
y = list(x)
y[1] = "kiwi"
x = tuple(y)

print(x)

('apple', 'kiwi', 'cherry')


EJERCICIO 29

In [2]:
tuple1 = ("a", "b" , "c")
tuple2 = (1, 2, 3)

tuple3 = tuple1 + tuple2
print(tuple3)

('a', 'b', 'c', 1, 2, 3)


EJERCICIO 30

In [3]:
fruits = ("apple", "banana", "cherry")
mytuple = fruits * 2

print(mytuple)

('apple', 'banana', 'cherry', 'apple', 'banana', 'cherry')


EJERCICIO 31

In [ ]:
thistuple = (1, 3, 7, 8, 7, 5, 4, 6, 8, 5)

x = thistuple.count(5)

print(x)

EJERCICIO 32

In [4]:
thistuple = (1, 3, 7, 8, 7, 5, 4, 6, 8, 5)

x = thistuple.index(8)

print(x)

3


EJERCICIO 33

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


EJERCICIO 34 MATRICES 2D 

In [4]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


EJERCICIO 35 MATRICES 3D

In [5]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


EJERCICIO 36 DIMENSIONES

In [6]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


EJERCICIO 37 NUMERO DE DIMENSIONES

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


EJERCICIO 38 INDEXAR 2D

In [11]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[1, 4])
print(arr)

2nd element on 1st row:  10
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


EJERICIO 39 INDEXAR 3D 

In [27]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr.ndim)
print(arr[0, 0, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
3


EJERCICIO 40 INDEXAR MATRIZ 3X3 EN 2D

In [28]:
import numpy as np

# Crear una matriz de ejemplo
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Acceder al elemento en la segunda fila y la tercera columna
elemento = matriz[1, 2]  # fila 1 (segunda fila), columna 2 (tercera columna)

print(elemento)  # Salida: 6
print(matriz)

6
[[1 2 3]
 [4 5 6]
 [7 8 9]]


EJERCICIO 41

In [32]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
print(arr[0, 1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[2 3 4]


EJERCICIO 42

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])


EJERCICIO 43

In [36]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:3, 1:4])

[[2 3 4]
 [7 8 9]]


EJERCICIO 44 INDEX

In [40]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr
[1:7:2]
)

[15 25 35]


EJERCICIO 45 INDEX

In [41]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr
[::2]
)

[10 20 30 40]


i -entero
b -booleano
u - entero sin signo
f -flotar
c - Flotador complejo
m - TimeDelta
M - fecha y hora
O -objeto
S -cuerda
U - Cadena Unicode
V - Se corrigió el trozo de memoria para otro tipo ( void )


EJERCICIO 46

In [42]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


Cambie el tipo de datos de float a integer utilizando como valor de parámetro:'i'

In [43]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


Cambie el tipo de datos de float a integer utilizando como valor de parámetro:int

In [44]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


Cambie el tipo de datos de entero a booleano:

In [45]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


Inserte el argumento correcto para especificar que la matriz debe ser de tipo STRING

In [48]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)

[b'1' b'2' b'3' b'4']


Haga una copia, cambie la matriz original y muestre ambas matrices:

In [49]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


Cree una vista, cambie la matriz original y muestre ambas matrices:

In [50]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


Imprima el valor del atributo base para comprobar si una matriz posee sus datos o no:

In [51]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


Imprime la forma de una matriz 2D:

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)


Use the correct NumPy method to change the shape of an array from 1-D to 2-D.

In [54]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(newarr)
newarr = arr.reshape(4, 3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Utilice un método NumPy correcto para cambiar la forma de una matriz de 2-D a 1-D.

In [56]:
arr = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
print(newarr)
newarr = arr.reshape(-1)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


Compruebe si la matriz devuelta es una copia o una vista:

In [57]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


Iterar en los elementos de la siguiente matriz 1D:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

Itere en los elementos de la siguiente matriz 2D:

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

Iterar en cada elemento escalar de la matriz 2D:

In [58]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


Itere en los elementos de la siguiente matriz 3D:

In [ ]:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

Iterar hasta los escalares:

In [59]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


Iterar a través de la siguiente matriz 3D:

In [60]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


Iterar a través de cada elemento escalar de la matriz 2D omitiendo 1 elemento:

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

Enumere los siguientes elementos de matrices 1D:

In [61]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


Enumere los siguientes elementos de la matriz 2D:

In [62]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


Unir dos matrices

In [63]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


Unir dos matrices 2D a lo largo de las filas (eje = 1):

In [65]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
print(arr1)
arr2 = np.array([[5, 6], [7, 8]])
print(arr2)
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


Apilamiento de matrices

In [66]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


Apilamiento por fila

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

Apilamiento por columna

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

Apilamiento a lo largo de la altura (profundidad)

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

Divida la matriz en 3 partes:

In [67]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


Divida la matriz en 4 partes:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

Acceda a las matrices divididas:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])


Divida la matriz 2D en tres matrices 2D.

In [ ]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

Divida la matriz 2D en tres matrices 2D.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

Divida la matriz 2D en tres matrices 2D a lo largo de filas.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

Utilice el método para dividir la matriz 2D en tres matrices 2D a lo largo de filas.hsplit()

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

Encuentre los índices en los que el valor es 4:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

Encuentre los índices en los que los valores son pares:

In [68]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


Encuentre los índices en los que los valores son impares:

In [69]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


Encuentre los índices en los que se debe insertar el valor 7:

In [70]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


Encuentre los índices en los que se debe insertar el valor 7, a partir de la Derecha:

In [ ]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

Encuentre los índices donde se deben insertar los valores 2, 4 y 6:

In [ ]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

Ordene la matriz:

In [ ]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

Ordene la matriz alfabéticamente:

In [ ]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

Ordene una matriz booleana:

In [ ]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

Si utiliza el método sort() en una matriz 2D, ambas matrices se ordenarán:

In [ ]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

Cree una matriz a partir de los elementos de los índices 0 y 2:

In [ ]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

Ejemplo
Cree una matriz de filtros que devuelva solo valores superiores a 42:

In [71]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


Cree una matriz de filtros que devuelva solo elementos pares del original arreglo:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

Cree una matriz de filtros que devuelva solo valores superiores a 42:

In [ ]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

Cree una matriz de filtros que devuelva solo elementos pares del original arreglo:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)